plugins {
    alias libs.plugins.android.library
}

android {
    namespace 'org.sufficientlysecure.htmltextview'

    compileSdk libs.versions.android.sdk.compile.get().toInteger()
    defaultConfig {
        minSdkVersion libs.versions.android.sdk.min.get()
        targetSdkVersion libs.versions.android.sdk.target.get()
        versionCode 14
        versionName '3.6'
    }
}

dependencies {
    implementation libs.androidx.appcompat
}
